logo: https://glimmer-styleguide.global.ssl.fastly.net/glimmer-styleguide/master/images/ember-logo.svg

sidebar:
  background: "#dd6a58"
  textColor: "#fff"

headHtml: |
  <meta name="ember-bootstrap-app/config/environment" content="%7B%22modulePrefix%22%3A%22ember-bootstrap-app%22%2C%22environment%22%3A%22development%22%2C%22rootURL%22%3A%22%2F%22%2C%22locationType%22%3A%22auto%22%2C%22EmberENV%22%3A%7B%22FEATURES%22%3A%7B%7D%2C%22EXTEND_PROTOTYPES%22%3A%7B%22Date%22%3Afalse%7D%7D%2C%22APP%22%3A%7B%22name%22%3A%22ember-bootstrap-app%22%2C%22version%22%3A%220.0.0%203802e264%22%7D%2C%22exportApplicationGlobal%22%3Atrue%7D">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://ember-bootstrap.surge.sh/assets/vendor.css">
  <link rel="stylesheet" href="https://ember-bootstrap.surge.sh/assets/ember-bootstrap-app.css">

bodyHtml: |
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://ember-bootstrap.surge.sh/assets/vendor.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.12.0/ember-template-compiler.js"></script>
  <script src="https://ember-bootstrap.surge.sh/assets/ember-bootstrap-app.js"></script>

emberAppName: EmberBootstrapApp
